"""
OPA integration via HTTP.

Communicates with OPA's REST API to evaluate policies and push
canvas-derived rules. OPA runs as a sidecar container.
"""

import httpx
from typing import Any

from app.core.config import get_settings
from app.core.logging import get_logger

logger = get_logger("ztforge.policy_engine")


class PolicyEngine:
    def __init__(self, opa_url: str | None = None, opa_token: str | None = None):
        self.opa_url = opa_url or get_settings().opa_url
        self.opa_token = opa_token or get_settings().opa_token
        self.headers = {"Authorization": f"Bearer {self.opa_token}"} if self.opa_token else {}

    async def evaluate(self, policy_path: str, input_data: dict[str, Any]) -> dict[str, Any]:
        """Query OPA for a policy decision."""
        url = f"{self.opa_url}/v1/data/{policy_path}"
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.post(url, json={"input": input_data}, headers=self.headers)
                resp.raise_for_status()
                return resp.json().get("result", {})
        except httpx.ConnectError:
            logger.warning("opa_unreachable", url=url)
            # Fail closed — deny by default when OPA is unreachable
            return {"allow": False, "reason": "Policy engine unreachable — defaulting to deny"}
        except httpx.HTTPStatusError as e:
            logger.error("opa_error", status=e.response.status_code, detail=str(e))
            return {"allow": False, "reason": f"Policy engine error: {e.response.status_code}"}

    async def push_policy(self, policy_id: str, rego_content: str) -> bool:
        """Push a Rego policy to OPA."""
        url = f"{self.opa_url}/v1/policies/{policy_id}"
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.put(
                    url,
                    content=rego_content,
                    headers={"Content-Type": "text/plain", **self.headers},
                )
                resp.raise_for_status()
                logger.info("policy_pushed", policy_id=policy_id)
                return True
        except (httpx.ConnectError, httpx.HTTPStatusError) as e:
            logger.error("policy_push_failed", policy_id=policy_id, error=str(e))
            return False

    async def push_data(self, data_path: str, data: dict[str, Any]) -> bool:
        """Push data to OPA's data store."""
        url = f"{self.opa_url}/v1/data/{data_path}"
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.put(url, json=data, headers=self.headers)
                resp.raise_for_status()
                return True
        except (httpx.ConnectError, httpx.HTTPStatusError) as e:
            logger.error("data_push_failed", path=data_path, error=str(e))
            return False

    async def health_check(self) -> bool:
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                resp = await client.get(f"{self.opa_url}/health", headers=self.headers)
                return resp.status_code == 200
        except httpx.ConnectError:
            return False


# ── Config Exporters ─────────────────────────────────────────
# Generate production configs from canvas state

def export_rego(nodes: list[dict], edges: list[dict], policies: list[dict]) -> str:
    """Generate an OPA-compatible Rego policy bundle from canvas."""
    lines = [
        "package ztforge.canvas",
        "",
        "import rego.v1",
        "",
        "# Auto-generated by ZTForge — do not edit manually",
        "# Regenerate from the canvas to update",
        "",
        "default allow := false",
        "",
    ]

    for edge in edges:
        policy = edge.get("policy", {})
        if policy.get("action") == "allow":
            src = edge["source"]
            tgt = edge["target"]
            conditions = policy.get("conditions", {})
            rule_name = f"allow_{src}_to_{tgt}".replace("-", "_")
            cond_lines = []
            if conditions.get("require_mfa"):
                cond_lines.append("    input.mfa_completed == true")
            if conditions.get("require_compliant_device"):
                cond_lines.append("    input.device_compliant == true")
            if conditions.get("require_valid_credential"):
                cond_lines.append("    input.has_valid_credential == true")

            lines.append(f"# {src} → {tgt}")
            lines.append(f"allow if {{")
            lines.append(f'    input.source == "{src}"')
            lines.append(f'    input.target == "{tgt}"')
            for cl in cond_lines:
                lines.append(cl)
            lines.append("}")
            lines.append("")

    return "\n".join(lines)


def export_pomerium_yaml(nodes: list[dict], edges: list[dict]) -> str:
    """Generate Pomerium proxy configuration from canvas edges."""
    lines = ["# ZTForge Pomerium Config", "# Auto-generated", "", "routes:"]
    for edge in edges:
        policy = edge.get("policy", {})
        if policy.get("action") == "allow":
            src_label = edge.get("source", "unknown")
            tgt_label = edge.get("target", "unknown")
            lines.append(f"  - from: https://{src_label}.internal")
            lines.append(f"    to: https://{tgt_label}.internal")
            lines.append(f"    policy:")
            lines.append(f"      - allow:")
            lines.append(f"          and:")
            lines.append(f"            - authenticated_user: true")
            conditions = policy.get("conditions", {})
            if conditions.get("require_mfa"):
                lines.append(f"            - claim/amr: mfa")
            lines.append("")
    return "\n".join(lines)


def export_terraform(nodes: list[dict], edges: list[dict]) -> str:
    """Generate Terraform network segmentation resources."""
    lines = [
        '# ZTForge Terraform Config',
        '# Auto-generated network segmentation',
        '',
        'terraform {',
        '  required_version = ">= 1.5"',
        '}',
        '',
    ]
    segments = set()
    for node in nodes:
        seg = node.get("data", {}).get("properties", {}).get("segment")
        if seg:
            segments.add(seg)

    for seg in sorted(segments):
        lines.append(f'resource "aws_security_group" "{seg}" {{')
        lines.append(f'  name        = "{seg}"')
        lines.append(f'  description = "ZTForge segment: {seg}"')
        lines.append(f'  vpc_id      = var.vpc_id')
        lines.append('}')
        lines.append('')

    for edge in edges:
        policy = edge.get("policy", {})
        if policy.get("action") == "allow":
            src, tgt = edge["source"], edge["target"]
            rule_name = f"allow_{src}_to_{tgt}".replace("-", "_")
            lines.append(f'resource "aws_security_group_rule" "{rule_name}" {{')
            lines.append(f'  type              = "ingress"')
            lines.append(f'  from_port         = 443')
            lines.append(f'  to_port           = 443')
            lines.append(f'  protocol          = "tcp"')
            lines.append(f'  security_group_id = aws_security_group.target.id')
            lines.append(f'  # source: {src} → target: {tgt}')
            lines.append('}')
            lines.append('')

    return "\n".join(lines)


def export_iptables(nodes: list[dict], edges: list[dict]) -> str:
    """Generate iptables rules from canvas edges."""
    lines = [
        "#!/bin/bash",
        "# ZTForge iptables rules — auto-generated",
        "# Apply with: sudo bash ztforge-iptables.sh",
        "",
        "# Flush existing rules",
        "iptables -F",
        "iptables -X",
        "",
        "# Default deny",
        "iptables -P INPUT DROP",
        "iptables -P FORWARD DROP",
        "iptables -P OUTPUT DROP",
        "",
        "# Allow loopback",
        "iptables -A INPUT -i lo -j ACCEPT",
        "iptables -A OUTPUT -o lo -j ACCEPT",
        "",
        "# Allow established connections",
        "iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT",
        "iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT",
        "",
    ]
    for edge in edges:
        policy = edge.get("policy", {})
        if policy.get("action") == "allow":
            src, tgt = edge["source"], edge["target"]
            lines.append(f"# {src} → {tgt}")
            lines.append(f"iptables -A FORWARD -s ${{IP_{src}}} -d ${{IP_{tgt}}} -p tcp --dport 443 -j ACCEPT")
            lines.append("")

    return "\n".join(lines)
